services:    
  streamrip:
        build: .
        container_name: streamrip
        user: "1000:1000" 
        environment:
          - HOME=/data/music
          - XDG_CONFIG_HOME=/data/music/.config
          - STREAMRIP_CONFIG=/data/music/.config/streamrip/config.toml
          - DOWNLOAD_DIR=/data/music
          - MAX_CONCURRENT_DOWNLOADS=2
        volumes:
          - /data/music/.config/streamrip:/data/music/.config/streamrip:rw
          - /data/music:/data/music:rw
        ports:
          - "5002:5000"
        restart: unless-stopped